### ISSUE TITLE
Electron build failed in @vue/cli 5

### ISSUE THREAD

**Issue by babsey** [nest-desktop/nest-desktop#336]
**Describe the bug**
After upgrading @vue/cli to 5, it failed to build electron. 

**Important remark: The CI job shows success even though it failed to build electron.**
See https://gitlab.ebrains.eu/nest/nest-desktop/-/jobs/23949

**To Reproduce**
```yarn electron:build```

**Expected behavior**
Electron builds (AppImage, snap)

**Logs**
```
-  Bundling main process...
 ERROR  Failed to compile with 1 errors10:34:54 AM
 error  in ./src/background.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/builds/nest/nest-desktop/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/builds/nest/nest-desktop/node_modules/ts-loader/dist/index.js:14:21)
 @ multi ./src/background.ts
Unhandled rejection Error: Build failed with errors.
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/index.js:198:21
    at finalCallback (/builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:257:39)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/nest/nest-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/nest/nest-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:271:21)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/nest/nest-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/nest/nest-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/nest/nest-desktop/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/nest/nest-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/builds/nest/nest-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/builds/nest/nest-desktop/node_modules/tapable/lib/Hook.js:154:20)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/builds/nest/nest-desktop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at /builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at done (/builds/nest/nest-desktop/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
    at tryCatcher (/builds/nest/nest-desktop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/builds/nest/nest-desktop/node_modules/bluebird/js/release/promise.js:547:31)
```

**Comment by babsey** [comment]
Close because we do not use vue/cli anymore. Instead we use Vite, which is faster.
